### ISSUE TITLE
New PRs being placed in the wrong GitHub milestone

### ISSUE THREAD

**Issue by edmorley** [buildpacks/pack#1352]
### Description
In PR #1350, a bot added the GitHub milestone [0.23.0](https://github.com/buildpacks/pack/milestone/35), however Pack CLI v0.23.0 has already been released. The milestone [0.24.0](https://github.com/buildpacks/pack/milestone/36) should have been added instead. In addition, the 0.23.0 milestone is showing as still open, when it should be closed.

### Proposed solution

- [ ] Update the bot to use the [0.24.0](https://github.com/buildpacks/pack/milestone/36) milestone instead
- [ ] Move out any PRs/issues in the old milestone that weren't actually shipped in the 0.23.0 release, and put them in 0.24.0
- [ ] Mark the 0.23.0 milestone as closed
- [ ] Update the Pack CLI release process playbook to cover the above steps, to help prevent this with future releases

**Comment by dfreilich** [comment]
Thanks for noting that! That was my fault, I should've closed the milestone after I released it

**Comment by edmorley** [comment]
I've just opened a new PR, and it was placed in the `0.24.1` milestone, even though that Pack version has already been released.

It looks like the new process wasn't followed for this latest release?
