### ISSUE TITLE
Support Platform API 0.9

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#1421]
## Summary

This is a tracking issue for all changes necessary to support Platform API 0.9.

- [Release Notes](https://github.com/buildpacks/spec/releases/tag/platform%2Fv0.9)

### Changes

- [x] https://github.com/buildpacks/pack/pull/1418
- [x] https://github.com/buildpacks/pack/issues/1390
- [x] https://github.com/buildpacks/pack/issues/1389
- [x] #1422
