### ISSUE TITLE
Support for new lifecycle descriptor

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#780]
### Description

Implement support for the new lifecycle.toml descriptor:

```toml
[apis]
[apis.buildpack]
  deprecated = []
  supported = ["0.2", "0.3", "0.4"]
[apis.platform]
  deprecated = []
  supported = ["0.3", "0.4"]

# For backwards compatibility the minimum supported APIs are provided in RFC-0011 format
# https://github.com/buildpacks/rfcs/blob/main/text/0011-lifecycle-descriptor.md
[api]
  platform = "0.3"
  buildpack = "0.2"

[lifecycle]
  version = "0.9.0"
```

### Proposed solution

If `[apis]` key is present, use solely the information in that table and ignore `[api]`, otherwise expect and use `[api]`.

### Additional context
- [ ] This feature should be documented somewhere

### Tasks

- [x] Read new format
- [x] Set new metadata to builder (incl old fields - [backwards compatibility][backward-compat])
- [x] Read new metadata from builder (falling back to old fields - [backwards compatibility][backward-compat])
- [x] Remove support for platform 0.2 (**breaking-change**)
- [x] Update inspect builder output to include `deprecated` and `supported`
- [x] Build using the latest supported version of the platform API
- [x] ~~Platform API 0.4: [api version in group.toml](https://github.com/buildpacks/spec/pull/120/files)~~
- [ ] Platform API 0.4: [remove version from BOM](https://github.com/buildpacks/spec/issues/107)
- [ ] Platform API 0.4: [removal of CNB_PROCESS_TYPE](https://github.com/buildpacks/rfcs/blob/main/text/0045-launcher-arguments.md#selecting-a-process-type-at-runtime)

Relates to https://github.com/buildpacks/lifecycle/pull/347

[backward-compat]: https://github.com/buildpacks/rfcs/blob/main/text/0049-multi-api-lifecycle-descriptor.md#backwards-compatibility
